// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexora.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexora.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NexoraDbContext))]
    [Migration("20261008122015_ImageMetadataAndDerivatives")]
    partial class ImageMetadataAndDerivatives
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<System.Guid>", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("bytea");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("CredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserPasskeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Nexora.Domain.Authentication.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId", "DeviceId");

                    b.ToTable("AuthSessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_AuthSessions_Expiration", "\"ExpiresAt\" > \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("Nexora.Domain.Authentication.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("Nexora.Domain.Authentication.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SuccessorId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SuccessorId")
                        .IsUnique();

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("SessionId", "SuccessorId");

                    b.ToTable("RefreshTokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_RefreshTokens_Consumption", "(\"UsedAt\" IS NULL) = (\"SuccessorId\" IS NULL)");

                            t.HasCheckConstraint("CK_RefreshTokens_Expiration", "\"ExpiresAt\" > \"CreatedAt\"");

                            t.HasCheckConstraint("CK_RefreshTokens_HashLength", "octet_length(\"TokenHash\") = 32");
                        });
                });

            modelBuilder.Entity("Nexora.Domain.Content.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlobId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BlobId");

                    b.HasIndex("OwnerId", "BlobId")
                        .IsUnique();

                    b.HasIndex("OwnerId", "DeletedAt");

                    b.HasIndex("OwnerId", "UploadedAt", "Id")
                        .IsDescending(false, true, true);

                    b.ToTable("Assets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Assets_DeletedAt", "\"DeletedAt\" IS NULL OR \"DeletedAt\" >= \"UploadedAt\"");
                        });
                });

            modelBuilder.Entity("Nexora.Domain.Content.Blob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetectedMimeType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .IsUnique();

                    b.ToTable("Blobs", null, t =>
                        {
                            t.HasCheckConstraint("CK_Blobs_Sha256", "\"Sha256\" ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("CK_Blobs_Size", "\"Size\" >= 0");

                            t.HasCheckConstraint("CK_Blobs_State", "\"State\" IN ('Staging', 'Ready', 'Deleting')");

                            t.HasCheckConstraint("CK_Blobs_StorageKey", "\"StorageKey\" = 'blobs/' || substring(replace(\"Id\"::text, '-', ''), 1, 2) || '/' || substring(replace(\"Id\"::text, '-', ''), 3, 2) || '/' || replace(\"Id\"::text, '-', '')");
                        });
                });

            modelBuilder.Entity("Nexora.Domain.Images.BlobImage", b =>
                {
                    b.Property<Guid>("BlobId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CapturedAtLocal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTimeOffset?>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DerivativeGenerationId")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<long?>("PreviewLength")
                        .HasColumnType("bigint");

                    b.Property<string>("PreviewSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ReservedBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<long?>("ThumbnailLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ThumbnailSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("BlobId");

                    b.HasIndex("DerivativeGenerationId")
                        .IsUnique();

                    b.HasIndex("State");

                    b.ToTable("BlobImages", null, t =>
                        {
                            t.HasCheckConstraint("CK_BlobImages_Metadata", "(\"State\" = 'Ready' AND \"Width\" IS NOT NULL AND \"Width\" > 0 AND \"Height\" IS NOT NULL AND \"Height\" > 0 AND \"ProcessedAt\" IS NOT NULL AND \"DerivativeGenerationId\" IS NOT NULL AND \"ThumbnailLength\" IS NOT NULL AND \"ThumbnailLength\" > 0 AND \"PreviewLength\" IS NOT NULL AND \"PreviewLength\" > 0 AND \"ThumbnailSha256\" IS NOT NULL AND \"ThumbnailSha256\" ~ '^[0-9a-f]{64}$' AND \"PreviewSha256\" IS NOT NULL AND \"PreviewSha256\" ~ '^[0-9a-f]{64}$') OR (\"State\" <> 'Ready' AND \"Width\" IS NULL AND \"Height\" IS NULL AND \"ProcessedAt\" IS NULL AND \"DerivativeGenerationId\" IS NULL AND \"ThumbnailLength\" IS NULL AND \"PreviewLength\" IS NULL AND \"ThumbnailSha256\" IS NULL AND \"PreviewSha256\" IS NULL AND \"CapturedAtLocal\" IS NULL AND \"CapturedAtUtc\" IS NULL)");

                            t.HasCheckConstraint("CK_BlobImages_Reservation", "\"ReservedBytes\" >= 0 AND (\"State\" <> 'Processing' OR \"ReservedBytes\" > 0)");

                            t.HasCheckConstraint("CK_BlobImages_State", "\"State\" IN ('Pending', 'Processing', 'Ready', 'Failed')");
                        });
                });

            modelBuilder.Entity("Nexora.Domain.Jobs.BackgroundJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BlobId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid");

                    b.Property<int>("MaximumAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<Guid?>("UploadSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BlobId")
                        .IsUnique();

                    b.HasIndex("UploadSessionId")
                        .IsUnique();

                    b.HasIndex("State", "LeaseExpiresAt");

                    b.HasIndex("State", "NextAttemptAt");

                    b.ToTable("BackgroundJobs", null, t =>
                        {
                            t.HasCheckConstraint("CK_BackgroundJobs_Attempts", "\"Attempts\" >= 0 AND \"MaximumAttempts\" BETWEEN 1 AND 100 AND \"Attempts\" <= \"MaximumAttempts\"");

                            t.HasCheckConstraint("CK_BackgroundJobs_Kind", "(\"Kind\" = 'FinalizeUpload' AND \"UploadSessionId\" IS NOT NULL AND \"BlobId\" IS NULL) OR (\"Kind\" = 'ProcessImage' AND \"BlobId\" IS NOT NULL AND \"UploadSessionId\" IS NULL)");

                            t.HasCheckConstraint("CK_BackgroundJobs_Lease", "\"State\" <> 'Running' OR (\"LeaseToken\" IS NOT NULL AND \"LeaseExpiresAt\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_BackgroundJobs_State", "\"State\" IN ('Pending', 'Running', 'Succeeded', 'Failed', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("Nexora.Domain.Jobs.BackgroundJobAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("BackgroundJobAttempts", (string)null);
                });

            modelBuilder.Entity("Nexora.Domain.Uploads.UploadChunk", b =>
                {
                    b.Property<Guid>("UploadSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TemporaryId")
                        .HasColumnType("uuid");

                    b.HasKey("UploadSessionId", "Number");

                    b.HasIndex("TemporaryId")
                        .IsUnique();

                    b.ToTable("UploadChunks", null, t =>
                        {
                            t.HasCheckConstraint("CK_UploadChunks_Hash", "\"Sha256\" ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("CK_UploadChunks_NumberSize", "\"Number\" >= 0 AND \"Size\" > 0");
                        });
                });

            modelBuilder.Entity("Nexora.Domain.Uploads.UploadSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long?>("AssemblyLength")
                        .HasColumnType("bigint");

                    b.Property<string>("AssemblyMimeType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("AssemblySha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.Property<Guid?>("AssemblyTemporaryId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("integer");

                    b.Property<int>("ChunkSize")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<long>("ExpectedLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ExpectedSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<long>("ReservedBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ResultAssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("AssemblyTemporaryId")
                        .IsUnique();

                    b.HasIndex("ResultAssetId");

                    b.HasIndex("OwnerId", "DeviceId");

                    b.HasIndex("OwnerId", "State");

                    b.HasIndex("State", "LastActivityAt");

                    b.ToTable("UploadSessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_UploadSessions_Activity", "\"LastActivityAt\" >= \"CreatedAt\"");

                            t.HasCheckConstraint("CK_UploadSessions_Assembly", "(\"AssemblyTemporaryId\" IS NULL AND \"AssemblyLength\" IS NULL AND \"AssemblySha256\" IS NULL AND \"AssemblyMimeType\" IS NULL) OR (\"AssemblyTemporaryId\" IS NOT NULL AND \"AssemblyLength\" IS NOT NULL AND \"AssemblyLength\" = \"ExpectedLength\" AND \"AssemblySha256\" IS NOT NULL AND \"AssemblySha256\" ~ '^[0-9a-f]{64}$' AND \"AssemblyMimeType\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_UploadSessions_Hash", "\"ExpectedSha256\" IS NULL OR \"ExpectedSha256\" ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("CK_UploadSessions_Length", "\"ExpectedLength\" BETWEEN 0 AND 4611686018427387903 AND \"ChunkSize\" BETWEEN 1 AND 67108864 AND \"ChunkCount\" BETWEEN 0 AND 65536 AND \"ChunkCount\" = (\"ExpectedLength\" + \"ChunkSize\" - 1) / \"ChunkSize\" AND \"ReservedBytes\" IN (0, \"ExpectedLength\" * 2)");

                            t.HasCheckConstraint("CK_UploadSessions_Result", "\"State\" <> 'Completed' OR \"ResultAssetId\" IS NOT NULL");

                            t.HasCheckConstraint("CK_UploadSessions_State", "\"State\" IN ('Open', 'Finalizing', 'Completed', 'Cancelled', 'Expired', 'Failed')");
                        });
                });

            modelBuilder.Entity("Nexora.Infrastructure.Identity.NexoraUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Nexora.Infrastructure.Identity.NexoraUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Nexora.Infrastructure.Identity.NexoraUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<System.Guid>", b =>
                {
                    b.HasOne("Nexora.Infrastructure.Identity.NexoraUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired();

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<bool>("IsBackedUp");

                            b1.Property<bool>("IsBackupEligible");

                            b1.Property<bool>("IsUserVerified");

                            b1.Property<string>("Name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired();

                            b1.Property<long>("SignCount");

                            b1.PrimitiveCollection<string>("Transports");

                            b1.HasKey("IdentityUserPasskeyCredentialId");

                            b1.ToTable("AspNetUserPasskeys");

                            b1
                                .ToJson("Data")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyCredentialId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexora.Infrastructure.Identity.NexoraUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Nexora.Infrastructure.Identity.NexoraUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nexora.Domain.Authentication.AuthSession", b =>
                {
                    b.HasOne("Nexora.Infrastructure.Identity.NexoraUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexora.Domain.Authentication.Device", "Device")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId", "DeviceId")
                        .HasPrincipalKey("UserId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Nexora.Domain.Authentication.Device", b =>
                {
                    b.HasOne("Nexora.Infrastructure.Identity.NexoraUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nexora.Domain.Authentication.RefreshToken", b =>
                {
                    b.HasOne("Nexora.Domain.Authentication.AuthSession", "Session")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexora.Domain.Authentication.RefreshToken", "Successor")
                        .WithMany()
                        .HasForeignKey("SessionId", "SuccessorId")
                        .HasPrincipalKey("SessionId", "Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Session");

                    b.Navigation("Successor");
                });

            modelBuilder.Entity("Nexora.Domain.Content.Asset", b =>
                {
                    b.HasOne("Nexora.Domain.Content.Blob", "Blob")
                        .WithMany("Assets")
                        .HasForeignKey("BlobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexora.Infrastructure.Identity.NexoraUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Blob");
                });

            modelBuilder.Entity("Nexora.Domain.Images.BlobImage", b =>
                {
                    b.HasOne("Nexora.Domain.Content.Blob", "Blob")
                        .WithOne("Image")
                        .HasForeignKey("Nexora.Domain.Images.BlobImage", "BlobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blob");
                });

            modelBuilder.Entity("Nexora.Domain.Jobs.BackgroundJob", b =>
                {
                    b.HasOne("Nexora.Domain.Content.Blob", "Blob")
                        .WithOne()
                        .HasForeignKey("Nexora.Domain.Jobs.BackgroundJob", "BlobId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Nexora.Domain.Uploads.UploadSession", "Upload")
                        .WithOne("Job")
                        .HasForeignKey("Nexora.Domain.Jobs.BackgroundJob", "UploadSessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Blob");

                    b.Navigation("Upload");
                });

            modelBuilder.Entity("Nexora.Domain.Jobs.BackgroundJobAttempt", b =>
                {
                    b.HasOne("Nexora.Domain.Jobs.BackgroundJob", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Nexora.Domain.Uploads.UploadChunk", b =>
                {
                    b.HasOne("Nexora.Domain.Uploads.UploadSession", "Session")
                        .WithMany("Chunks")
                        .HasForeignKey("UploadSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Nexora.Domain.Uploads.UploadSession", b =>
                {
                    b.HasOne("Nexora.Infrastructure.Identity.NexoraUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexora.Domain.Content.Asset", "ResultAsset")
                        .WithMany()
                        .HasForeignKey("ResultAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nexora.Domain.Authentication.Device", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "DeviceId")
                        .HasPrincipalKey("UserId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResultAsset");
                });

            modelBuilder.Entity("Nexora.Domain.Authentication.AuthSession", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Nexora.Domain.Authentication.Device", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Nexora.Domain.Content.Blob", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Nexora.Domain.Uploads.UploadSession", b =>
                {
                    b.Navigation("Chunks");

                    b.Navigation("Job");
                });
#pragma warning restore 612, 618
        }
    }
}
